/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import java.util.List;
import ec.edu.ups.controlador.ControladorDirectorio;
import java.io.File;
import java.text.DecimalFormat;
/**
 *
 * @author Dutan2000
 */
public class GestionarDirectorios extends javax.swing.JInternalFrame {
    private ControladorDirectorio controladorDirectorio;
    /**
     * Creates new form GestionarDirectorios
     */
    public GestionarDirectorios(ControladorDirectorio controladorD) {
        initComponents();
        controladorDirectorio=controladorD;
    }
    public void listar(List<String> listaDeArchivos){
        int aux=0;
        String vector[]= new String[listaDeArchivos.size()];
        for (String archivo : listaDeArchivos) {
            vector[aux]=archivo;
            aux=aux+1;
        }
     listaDeDatos.setListData(vector);
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRuta = new javax.swing.JTextField();
        botonListarD = new javax.swing.JButton();
        botonListarArchivosOcultos = new javax.swing.JButton();
        botonListarDirectorios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeDatos = new javax.swing.JList<>();
        botonMostrarInformacion = new javax.swing.JButton();
        botonListarA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        txtRuta.setText("/Users/Practica");

        botonListarD.setText("Listar Directorios");
        botonListarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarDActionPerformed(evt);
            }
        });

        botonListarArchivosOcultos.setText("Listar Archivos Ocultos");
        botonListarArchivosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarArchivosOcultosActionPerformed(evt);
            }
        });

        botonListarDirectorios.setText("Listar Directorios Ocultos");
        botonListarDirectorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarDirectoriosActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaDeDatos);

        botonMostrarInformacion.setText("Mostrar Informacion");
        botonMostrarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarInformacionActionPerformed(evt);
            }
        });

        botonListarA.setText("Listar Archivos");
        botonListarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarAActionPerformed(evt);
            }
        });

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(204, 204, 204));
        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setText("INFORMACION:\n\n");
        jScrollPane2.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonListarA, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonListarD, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonListarArchivosOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(botonMostrarInformacion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonListarDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonListarA)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonListarD)
                        .addComponent(botonListarArchivosOcultos)
                        .addComponent(botonListarDirectorios)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(botonMostrarInformacion)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarDActionPerformed
        String ruta=txtRuta.getText();
        File directorio=new File(ruta);
        listar(controladorDirectorio.listarDirectorios(directorio));

    }//GEN-LAST:event_botonListarDActionPerformed

    private void botonListarArchivosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarArchivosOcultosActionPerformed
        String ruta=txtRuta.getText();
        File archivoOculto=new File(ruta);
        listar(controladorDirectorio.listarArchivosOcultos(archivoOculto));
    }//GEN-LAST:event_botonListarArchivosOcultosActionPerformed

    private void botonListarDirectoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarDirectoriosActionPerformed
        String ruta=txtRuta.getText();
        File directorioOculto=new File(ruta);
        listar(controladorDirectorio.listarArchivosOcultos(directorioOculto));

    }//GEN-LAST:event_botonListarDirectoriosActionPerformed

    private void botonMostrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarInformacionActionPerformed
        String archivo=txtRuta.getText()+"/"+listaDeDatos.getSelectedValue();
        File ruta = new File(archivo);
        String informacion=controladorDirectorio.mostrarInformacion(ruta);
        String lectura="";
        String escritura="";
        if(ruta.canRead()){
            lectura="Verdadero";
        }else{
           lectura="Falso";
        }
        if(ruta.canWrite()){
            escritura="Verdadero";
        }else{
           escritura="Falso"; 
        }
        DecimalFormat formato = new DecimalFormat("#0.000");
        String tamaño=formato.format(controladorDirectorio.tamañoDeDirectorio(ruta));
        
        txtArea.setText(archivo +"\nTamaño de Archivo: "+tamaño +"\nAcceso de Lectura: "+escritura+"\nAcceso de escritura: "+escritura+"\nUltima fecha modificada: "+ informacion);

    }//GEN-LAST:event_botonMostrarInformacionActionPerformed

    private void botonListarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarAActionPerformed
        String ruta= txtRuta.getText();
        File archivo=new File(ruta);
        listar(controladorDirectorio.listarArchivos(archivo));

    }//GEN-LAST:event_botonListarAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonListarA;
    private javax.swing.JButton botonListarArchivosOcultos;
    private javax.swing.JButton botonListarD;
    private javax.swing.JButton botonListarDirectorios;
    private javax.swing.JButton botonMostrarInformacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaDeDatos;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
